# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 352767874cc46eddfe901513b6b5c900e0aea3b643bf69fbc2e30e97a4888030ccccc07a76bc6f0045bdcb3785c87311e7bea324dc71894bca660a22f8209707

test:
  secret_key_base: f05bed357a98e8dd98e380f1beddc611aba26891adab0c7c895247e3a8cd826de76c4d03062b71e7a2362d7583a81df8e05394c532800112f6b9cd1c4ea24ba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
